# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ebf5d6cba450fcb7d9447fa6f390776e092c1de9ed20ec44895ccfdb860ddbee334bae1ebc42adac77df9d834f96bce194417f3aa097d85e3620ca40643c7e0

test:
  secret_key_base: 8e044cab706b46901f15113d4c55247d40d37b5a950538ff5ec9cf6577eaacffbe4da88203cbb8b613ec9beceed62ab8f6bac7a0be34dfec84a0ec2475bd25cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
